### ISSUE TITLE
キックオフ資料作成

### ISSUE THREAD

**Issue by yosamura** [yosamura/project_abic#1]
銀行向けキックオフ資料を作成する
```yaml
start_date: 2023/2/27
due_date: 2023/3/31
parent: 0
```
